#!/bin/bash


#LD_LIBRARY_PATH is set and will mess up ffmpeg, unset it, then re-set it when done
ldPath=${LD_LIBRARY_PATH}
unset LD_LIBRARY_PATH

infile=$1
outfile=$infile

exitcode=0

if [[ $# -lt 1 ]]; then

  exename=$(basename "$0")

  echo "Remove commercial from video file using EDL file"
  echo "     (If no EDL file is found, comskip will be used to generate one)"
  echo ""
  echo "Usage: $exename infile [outfile]"

  exit 1
fi

if [[ $# -lt 2 ]]; then
  outfile="$1"
else
  outfile="$2"
fi

comskipini=$HOME/.comskip.ini

if [ ! -f "$comskipini" ]; then
  echo "output_edl" > "$comskipini"
elif ! grep -q "output_edl=1" "$comskipini"; then
  echo "output_edl=1" >> "$comskipini"
fi

outdir=$(dirname "$outfile")

outextension="${outfile##*.}"

edlfile="${infile%.*}.edl"
metafile="${infile%.*}.ffmeta"
logfile="${infile%.*}.log"
logofile="${infile%.*}.logo.txt"
txtfile="${infile%.*}.txt"

deleteedl=true
deletemeta=true
deletelog=true
deletelogo=true
deletetxt=true

if [ ! -f "$edlfile" ]; then
  comskip --ini="$comskipini" "$infile"
fi

start=0
i=0
hascommercials=false

concat=""

tempfiles=()
totalcutduration=0

echo ";FFMETADATA1" > "$metafile"
# Reads in from $edlfile, see end of loop.
while IFS=$'\t' read -r -a line
do
  ((i++))

  end="${line[0]}"
  duration=`echo "$end" - "$start" | bc`
  startnext="${line[1]}"

  hascommercials=true

  echo [CHAPTER] >> "$metafile"
  echo TIMEBASE=1/1 >> "$metafile"
  echo START=`echo "$start" - "$totalcutduration" | bc` >> "$metafile"
  echo END=`echo "$end" - "$totalcutduration" | bc` >> "$metafile"

  chapterfile=`mktemp --suffix=.ts "$outdir"/chapter-"$i"-XXXXXXXX`
  tempfiles+=("$chapterfile")
  concat="$concat|$chapterfile"

  #echo ffmpeg -nostdin -i "\"$infile\"" -ss "$start" -t "$duration" -c copy -y "$chapterfile"
  ffmpeg -nostdin -i "$infile" -ss "$start" -t "$duration" -c copy -y "$chapterfile"

  totalcutduration=`echo "$totalcutduration" + "$startnext" - "$end" | bc`
  start=$startnext
done < "$edlfile"

if $hascommercials ; then
  #echo ffmpeg -nostdin -i "$metafile" -i "concat:${concat:1}" -c copy -map_metadata 0 -y "$outfile"
  ffmpeg -nostdin -i "$metafile" -i "concat:${concat:1}" -c copy -map_metadata 0 -y "$outfile"
fi

for i in "${tempfiles[@]}"
do
  rm "$i"
done

if $deleteedl ; then rm "$edlfile"; fi

if $deletemeta ; then rm "$metafile"; fi

if $deletelog ; then rm "$logfile"; fi

if $deletelogo ; then rm "$logofile"; fi

if $deletetxt ; then rm "$txtfile"; fi

if [ ! -z $ldPath ] ; then
  #re-set LD_LIBRARY_PATH
  export LD_LIBRARY_PATH="$ldPath"
fi
